version: '3'

services:
  training_pipeline:
    image: training_compfest:v1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DAGSHUB_KEY=${DAGSHUB_KEY}
        - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
        - MLFLOW_TRACKING_USERNAME=${MLFLOW_TRACKING_USERNAME}
        - MLFLOW_TRACKING_PASSWORD=${MLFLOW_TRACKING_PASSWORD}

    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      - MLFLOW_TRACKING_USERNAME=${MLFLOW_TRACKING_USERNAME}
      - MLFLOW_TRACKING_PASSWORD=${MLFLOW_TRACKING_PASSWORD}
    
    command: ["python", "main.py", "--train"]