version: '3'

services:
  neo4j:
    container_name: neo4j
    image: neo4j:5.22.0
    environment:
      - NEO4J_AUTH=neo4j/admin123
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j_db/data:/data
      - ./neo4j_db/logs:/logs
      - ./neo4j_db/import:/var/lib/neo4j/import
      - ./neo4j_db/plugins:/plugins
      
  # prepare-kg:
  #   container_name: prepare_kg
  #   build: .
  #   environment:
  #     - KAGGLE_USERNAME=${KAGGLE_USERNAME}
  #     - KAGGLE_KEY=${KAGGLE_KEY}
  #     - NEO4J_URI=${NEO4J_URI}
  #     - NEO4J_USER=${NEO4J_USER}
  #     - NEO4J_PASSWORD=${NEO4J_PASSWORD}
  #     - NEO4J_DB=${NEO4J_DB}
  #   volumes:
  #     - ./neo4j_db/import:/app/dataset